# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('length', models.IntegerField()),
                ('venomous', models.BooleanField(default=False)),
            ],
        ),
    ]
